In [9]:
import pandas as pd

jobs = pd.read_excel("data/indian-job-market-dataset-2025.xlsx")
print("Shape:", jobs.shape)
jobs.head(3)

Shape: (97929, 17)

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0

In [11]:
clean = jobs.dropna(subset=["tagsAndSkills", "minimumExperience", "maximumExperience"])

clean["skills_list"] = clean["tagsAndSkills"].apply(lambda x: [s.strip() for s in x.split(",")])

clean["minimumSalary"] = clean["minimumSalary"].replace(0, None)
clean["maximumSalary"] = clean["maximumSalary"].replace(0, None)

print("Before cleaning:", jobs.shape[0], "rows")
print("After cleaning:", clean.shape[0], "rows")
clean[["title", "skills_list", "minimumExperience", "maximumExperience"]].head(5)

Before cleaning: 97929 rows
After cleaning: 97358 rows

,title,skills_list,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),"[Communication, Manpower, Staffing, Convincing...",2.0,4.0
1,Fire And Safety Officer,"[Safety Officer Activities, Fire Protection, F...",6.0,11.0
2,Opening For Performance Marketing - Chennai,"[Performance Marketing, User Acquisition, grow...",12.0,18.0
3,Medical Billing Executive,"[Fluent English, Spoken English, Good English ...",0.0,3.0
4,Senior Group Product Manager - CNS Therapy,"[Product Marketing, CNS, Product Management, N...",5.0,10.0

In [8]:
clean.to_csv("data/cleaned_jobs.csv", index=False)
print("Saved cleaned dataset!")

Saved cleaned dataset!